name: Run Nodes Integration Tests

on:
  workflow_dispatch:

jobs:
  run-nodes:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (pnpm)
        run: |
          npm install -g pnpm@8
          pnpm install -w

      - name: Ensure pnpm-only lock files
        run: |
          set -ex
          # fail CI if any package-lock.json is present to enforce pnpm-only
          if git ls-files '*package-lock.json' | grep -q package-lock.json; then echo "Found package-lock.json - use pnpm and remove package-lock.json." && exit 1; fi

      - name: Start ns-node (3000)
        run: |
          node neuroswarm/ns-node/server.js --status > ns.log 2> ns.err & echo $! > ns.pid

      - name: Wait for ns-node health
        run: |
          set -ex
          for i in 1 2 3 4 5; do
            if curl --silent --fail http://localhost:3000/health; then exit 0; fi
            sleep 1
          done
          echo 'ns-node failed to become healthy' && exit 1

      - name: Wait for gateway to detect ns (peers.nsOk)
        run: |
          set -ex
          for i in 1 2 3 4 5 6 7 8 9 10; do
            out=$(curl --silent --fail http://localhost:8080/debug/peers || true)
            echo "peers: $out"
            if echo "$out" | grep -q '"nsOk":true'; then echo 'gateway sees ns' && exit 0; fi
            sleep 1
          done
          echo 'gateway did not detect ns' && exit 1

      - name: Start gateway-node (8080)
        env:
          NS_CHECK_EXIT_ON_FAIL: 'false'
          NS_NODE_URL: 'http://localhost:3000'
        run: |
          node neuroswarm/gateway-node/server.js --status > gw.log 2> gw.err & echo $! > gw.pid

      - name: Wait for gateway health
        run: |
          set -ex
          for i in 1 2 3 4 5; do
            if curl --silent --fail http://localhost:8080/health; then exit 0; fi
            sleep 1
          done
          echo 'gateway failed to become healthy' && exit 1

      - name: Start vp-node (4000)
        env:
          NS_NODE_URL: 'http://localhost:3000'
        run: |
          node neuroswarm/vp-node/server.js --status > vp.log 2> vp.err & echo $! > vp.pid

      - name: Wait for vp-node registration (validator list)
        run: |
          set -ex
          for i in 1 2 3 4 5 6 7 8 9 10; do
            if curl --silent --fail http://localhost:3000/validators; then exit 0; fi
            sleep 1
          done
          echo 'vp-node failed to register validator' && exit 1

      - name: Run connectivity script (CI)
        run: |
          node neuroswarm/scripts/checkNodeConnectivityClean.mjs --ns http://localhost:3000 --gateway http://localhost:8080 --timeout 2000 --ci

      - name: Confirm heartbeats in logs
        run: |
          node neuroswarm/scripts/confirm-heartbeat-from-logs.mjs

      - name: 'Smoke test - produce a block and verify acceptance'
        run: |
          set -ex
          node neuroswarm/scripts/smokeProduce.mjs

      - name: Run consensus tests (neuro-services) - unit
        run: |
          pnpm -C neuro-services test:ci

      - name: Run PoS integration tests (neuro-services) - specific
        run: |
          pnpm -C neuro-services test -- tests/pos-multi-equivocation.test.ts tests/pos-signature-verify.test.ts tests/pos-reorg-extended.test.ts tests/pos-long-range.test.ts tests/gateway-startup-retry.test.ts --runInBand

      - name: Upload PoS test results (if exists)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pos-test-logs
          path: |
            neuro-services/test-results
            neuro-services/coverage

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nodes-logs
          path: |
            ns.log
            ns.err
            gw.log
            gw.err
            vp.log
            vp.err

      - name: Teardown
        if: always()
        run: |
          if [ -f ns.pid ]; then kill $(cat ns.pid) || true; fi
          if [ -f gw.pid ]; then kill $(cat gw.pid) || true; fi
          if [ -f vp.pid ]; then kill $(cat vp.pid) || true; fi

      - name: Lint: disallow raw console.* in runtime node sources
        run: |
          set -ex
          # Find raw console.* uses in runtime sources (neuroswarm/*-node), excluding the log wrapper definitions
          matches=$(git grep -n -- 'console\.\(log\|warn\|error\)' -- neuroswarm/*-node || true)
          filtered=$(printf "%s" "$matches" | grep -v -E 'function log|/public/|start-windows.bat|\[GW\]|\[NS\]|\[VP\]' || true)
          if [ -n "$filtered" ]; then echo "Found console.* in node runtimes:"; echo "$filtered"; exit 1; fi

      - name: Package artifacts and verify Windows start scripts
        run: |
          set -ex
          pnpm -C neuroswarm package:bins
          # Validate zip artifacts contain start-windows.bat and that it contains 'cmd /k'
          for z in neuroswarm/dist/*.zip; do
            echo "Validating $z"
            if ! unzip -l "$z" | grep -q 'start-windows.bat'; then echo "Missing start-windows.bat in $z" && exit 1; fi
            tmpdir=$(mktemp -d)
            unzip -q "$z" -d "$tmpdir"
            # find start-windows.bat inside the unzipped folder and assert content
            batfile=$(find "$tmpdir" -type f -name 'start-windows.bat' | head -n 1 || true)
            if [ -z "$batfile" ]; then echo "No start-windows.bat extracted from $z" && exit 1; fi
            if ! grep -q 'cmd /k' "$batfile"; then echo "start-windows.bat in $z does not use 'cmd /k'" && exit 1; fi
            if ! grep -q -- '--status' "$batfile"; then echo "start-windows.bat in $z does not pass --status by default" && exit 1; fi
            rm -rf "$tmpdir"
          done

  run-nodes-reverse:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: run-nodes
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies (pnpm)
        run: |
          npm install -g pnpm@8
          pnpm install -w

      - name: Ensure pnpm-only lock files
        run: |
          set -ex
          if git ls-files '*package-lock.json' | grep -q package-lock.json; then echo "Found package-lock.json - use pnpm and remove package-lock.json." && exit 1; fi

      - name: Start gateway-node first (8080)
        env:
          NS_CHECK_EXIT_ON_FAIL: 'false'
          NS_NODE_URL: 'http://localhost:3000'
        run: |
          node neuroswarm/gateway-node/server.js > gw.log 2> gw.err & echo $! > gw.pid

      - name: Wait for gateway health
        run: |
          set -ex
          for i in 1 2 3 4 5; do
            if curl --silent --fail http://localhost:8080/health; then exit 0; fi
            sleep 1
          done
          echo 'gateway failed to become healthy' && exit 1

      - name: Start ns-node (3000)
        run: |
          node neuroswarm/ns-node/server.js > ns.log 2> ns.err & echo $! > ns.pid

      - name: Wait for ns-node health
        run: |
          set -ex
          for i in 1 2 3 4 5; do
            if curl --silent --fail http://localhost:3000/health; then exit 0; fi
            sleep 1
          done
          echo 'ns-node failed to become healthy' && exit 1

      - name: Start vp-node (4000)
        env:
          NS_NODE_URL: 'http://localhost:3000'
        run: |
          node neuroswarm/vp-node/server.js > vp.log 2> vp.err & echo $! > vp.pid

      - name: Wait for vp-node registration (validator list)
        run: |
          set -ex
          for i in 1 2 3 4 5 6 7 8 9 10; do
            if curl --silent --fail http://localhost:3000/validators; then exit 0; fi
            sleep 1
          done
          echo 'vp-node failed to register validator' && exit 1

      - name: Run connectivity script (CI)
        run: |
          node neuroswarm/scripts/checkNodeConnectivityClean.mjs --ns http://localhost:3000 --gateway http://localhost:8080 --timeout 2000 --ci

      - name: 'Smoke test - produce a block and verify acceptance'
        run: |
          set -ex
          node neuroswarm/scripts/smokeProduce.mjs

      - name: Upload logs (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: nodes-logs-reverse
          path: |
            ns.log
            ns.err
            gw.log
            gw.err
            vp.log
            vp.err

      - name: Teardown
        if: always()
        run: |
          if [ -f ns.pid ]; then kill $(cat ns.pid) || true; fi
          if [ -f gw.pid ]; then kill $(cat gw.pid) || true; fi
          if [ -f vp.pid ]; then kill $(cat vp.pid) || true; fi
